"""Tests for secure random generation."""

import pytest

from marauder.crypto.random import generate_random_bytes


class TestGenerateRandomBytes:
    """Test secure random byte generation."""

    def test_correct_length(self):
        """Generated bytes should match requested length."""
        for length in [1, 16, 32, 64, 128]:
            result = generate_random_bytes(length)
            assert len(result) == length

    def test_uniqueness(self):
        """Multiple calls should produce different values."""
        # Generate multiple random byte sequences
        samples = [generate_random_bytes(32) for _ in range(100)]
        # All should be unique (very high probability)
        unique_samples = set(samples)
        assert len(unique_samples) == len(samples)

    def test_entropy_basic(self):
        """Basic statistical test for randomness."""
        # Generate a large sample
        sample = generate_random_bytes(1000)
        # Check that bytes are not all the same value
        unique_bytes = set(sample)
        # With 1000 random bytes, we should have many unique values
        # (probability of all being same is negligible)
        assert len(unique_bytes) > 1

    def test_invalid_length_negative(self):
        """Negative length should raise ValueError."""
        with pytest.raises(ValueError, match="Length must be at least 1"):
            generate_random_bytes(-1)

    def test_invalid_length_zero(self):
        """Zero length should raise ValueError."""
        with pytest.raises(ValueError, match="Length must be at least 1"):
            generate_random_bytes(0)


